### ISSUE TITLE
Unable to Connect to Firebase Database

### ISSUE THREAD

**Issue by OmphilegapeMbelle** [SeanWits/Malumez#1]
Hi there!

I am having trouble getting the users information from the database and displaying it on the screen. Any help will be appreciated.

**Comment by ValerieC123** [comment]
I'd take some code from other instances of database access:

`import { db } from "../firebase";
import { getDocs, collection } from "firebase/firestore";`
  at the top of the admin.js the page to access the database itself.

And maybe access the info this way:  (I'm still figuring out how to format my comments here so make sure you have the whole function)

```jsx

 function InfoAccess() {
 const [<DataToGet>, set<DataToGet>] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            try {
                // Query all documents from the "shops" collection
                const querySnapshot = await getDocs(collection(db, "<Name of object you want to access>"));
                const data = [];

                // Iterate over the documents and extract the data
                querySnapshot.forEach((doc) => {
                    const { <The paramaters/ properties of the particular data you want to get> } = doc.data();
                    data.push({ <The paramaters/ properties of the particular data you want to get> });
                });

                // Set the extracted data to state
                set<DataToGet>(data);
            } catch (error) {
                console.error("Error fetching data:", error);
            }
        };

        // Call the Data function when the component mounts
         fetchData();

        // Cleanup function (optional)
        return () => {
            // Perform cleanup if necessary
        };
    }, []);

    return (
        <div>
            {/* Your page JSX here */}
        </div>
    );}  

```

You'll have to make edits to this and put in your own function names, variables, parameters etc but I took this straight from some of the code we are using in our project. At the end of the day, having a look at the [Firebase API](https://firebase.google.com/docs/firestore/query-data/get-data) .
may also give you some more information about how to access, create and change any data you need.

**Comment by ValerieC123** [comment]
Is your issue sorted? If so, you can close the issue as resolved
