### ISSUE TITLE
footer doesn't stay at the bottom of the page for checkout page

### ISSUE THREAD

**Issue by refiloemopeloa** [SeanWits/Malumez#12]
![Screenshot (24)](https://github.com/SeanWits/Malumez/assets/72868391/84d94b70-2fac-4d31-a2ce-196df822e6f4)

**Comment by aioniaeftychia** [comment]
fixed by adding the following code to the css
```
bottom: 0;
position: fixed;
width: 100%;
```

**Comment by refiloemopeloa** [comment]
fixed by adding the following code to the css
```
bottom: 0;
position: fixed;
width: 100%;
```

**Comment by refiloemopeloa** [comment]
Footer stays at the bottom of the page but hides content at the bottom of the page

**Comment by refiloemopeloa** [comment]
fixed by removing body element from header file
