### ISSUE TITLE
One of the pages is causing an infinite amount of writes to the firestore database.

### ISSUE THREAD

**Issue by SeanWits** [SeanWits/Malumez#19]
![Screenshot_20240508_074100](https://github.com/SeanWits/Malumez/assets/162125074/4722525f-7f51-4176-883d-37d5b7ebd17c)

**Comment by ValerieC123** [comment]
It seems that everytime the product page runs (Which it does constantly) it calls the Database and repopulates the page all over again. What needs to happen as React should only update the pages when the product page changes rather than reloading everything every 3 or so seconds

**Comment by ValerieC123** [comment]
I've configured it so that the fetchProducts functions runs asynchronously instead of continuously. This seems to have fixed the issue and the writes are much less now. Hopefully we won't encounter this issue again
