### ISSUE TITLE
home page>>view more>>add items to cart>> checkout>> continue shopping breaks the website

### ISSUE THREAD

**Issue by refiloemopeloa** [SeanWits/Malumez#20]
![Screenshot (27)](https://github.com/SeanWits/Malumez/assets/72868391/46e22c7f-c81b-40f5-9e33-2be0d83b69ac)

**Comment by ValerieC123** [comment]
Fixed. The page was listening out for the Search button to be clicked but the button didn't exist yet so it was reading a null object, causing an error. This was fixed by introducing a question mark for the event listener to check whether the searchButton was null first
