### ISSUE TITLE
ShowProducts function not working as intended

### ISSUE THREAD

**Issue by SeanWits** [SeanWits/Malumez#3]
Everytime ShowProducts function is called, it occurs twice causing a delay in fetching data.

**Comment by ValerieC123** [comment]
Where is the function located?

**Comment by ValerieC123** [comment]
How did you fix this problem? I am having the same one when I try to fetch the brands

**Comment by ValerieC123** [comment]
Nvm fixed it

**Comment by ValerieC123** [comment]
It's sorted now : )
