### ISSUE TITLE
home page front-end is broken

### ISSUE THREAD

**Issue by refiloemopeloa** [SeanWits/Malumez#5]
The home page is not displaying how it used to .

**Comment by refiloemopeloa** [comment]
login.css was found to be causing the issue

**Comment by refiloemopeloa** [comment]
login.css was setting the attributes of objects, which carried over the entire website. attempting to change all object attributes to class attributes.

**Comment by aioniaeftychia** [comment]
changing object attributes to class attributes fixed home page

**Comment by refiloemopeloa** [comment]
changing object attributes to class attributes fixed home page
